name: Tests Library build and publish

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Build library
              run: npm run build

            - name: Publish dry run
              run: npm publish --dry-run
